### ISSUE TITLE
@elseif instead of @else if

### ISSUE THREAD

**Issue by aaitmouloud** [Igosuki/compass-mixins#103]
Hello,

When trying to compile a project using `dart-sass` and `compass-mixins`, i had the following error:

> Compiling scss/main.scss :
> Error: This at-rule is not allowed here.
>     } @elseif type-of($item) == 'color' {
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   scss/compass/functions/_cross_browser_support.scss 12:7

When reading the SASS documentation, it seems that the "else if" logic must be written as `@else if` and not as `@elseif` (http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#_9)

When using the "correct" from, the compilation works with `dart-sass`.

When running a [search on @elseif](https://github.com/Igosuki/compass-mixins/search?utf8=%E2%9C%93&q=elseif&type=Code) presence in the repository, it seems that the only file concerned is [_cross_browser_support.scss](https://github.com/Igosuki/compass-mixins/blob/master/lib/compass/functions/_cross_browser_support.scss) on lines 12 and 13.

**Comment by graphicmist** [comment]
This is such an old issue and still open?

**Comment by aequasi** [comment]
Seems this repo is dead. Last commit 2 years ago

**Comment by mileslane** [comment]
Sadly.  I am encountering this as well.

**Comment by graphicmist** [comment]
People please stop using this library. This was created way too in the past & I don't feel the need of using compass mixins now since it is not maintained. Also, finding it being used by other repos is a pain in itself.

**Comment by wadiddy** [comment]
> People please stop using this library. This was created way too in the past & I don't feel the need of using compass mixins now since it is not maintained. Also, finding it being used by other repos is a pain in itself.

what alternative library do you suggest?

**Comment by Igosuki** [comment]
I did the merge for posterity, the maintainers who took over stopped maintaining the library a few years ago.
