### ISSUE TITLE
Please publish v0.12.11 on npm

### ISSUE THREAD

**Issue by boarwell** [Igosuki/compass-mixins#119]
Hello @Igosuki 

Thank you very much for your great work. Our team has been using this for several years now.

When we updated Sass, we noticed `@elseif-warning` (cf. https://github.com/Igosuki/compass-mixins/issues/103) in the log. Fortunately this has been fixed in v0.12.11, but it doesn't seem to be published on npm yet, I know README says "This library is not maintained anymore.", but could you please publish it on npm?

**Comment by Igosuki** [comment]
Published https://www.npmjs.com/package/compass-mixins
