### ISSUE TITLE
Please publish v0.12.12 on npm

### ISSUE THREAD

**Issue by hiratsuka-r** [Igosuki/compass-mixins#123]
Hello @Igosuki

Thank you for your support during this time.
issues: https://github.com/Igosuki/compass-mixins/issues/121
PR: https://github.com/Igosuki/compass-mixins/pull/122

Please publish it on npm?
I'd appreciate it if you would give me a reply when you have time. Thank you.

**Comment by Igosuki** [comment]
Done

**Comment by jonassmedegaard** [comment]
please tag the release in git

**Comment by Igosuki** [comment]
I tagged it but forgot to push. Will do when I get home

**Comment by Igosuki** [comment]
Done
