### ISSUE TITLE
New release..?

### ISSUE THREAD

**Issue by shmax** [Igosuki/compass-mixins#124]
Hey there, I understand that this repo isn't maintained anymore, but is there any way I can trouble you to bump a new release so that we can get https://github.com/Igosuki/compass-mixins/pull/122? Much appreciated, and thanks for a great library.

**Comment by Igosuki** [comment]
Hi, that PR has been live in the latest release since June, it's also on npm. Let me know if there's anything more you need. Closing for now.

**Comment by shmax** [comment]
Ah, it seems you're right; not sure what happened on my end, but I just removed and re-installed your package and now it seems to work just fine. Thanks much.

**Comment by Igosuki** [comment]
Cool !
