### ISSUE TITLE
"Sass -> CSS (may only compare numbers)" error when using with node-sass

### ISSUE THREAD

**Issue by PandaWhisperer** [Igosuki/compass-mixins#17]
I am attempting to replace compass in my Node.js project with a pure JS-based solution. So I installed the `compass-mixins` module and symlinked it into my stylesheets directory. 

I am seeing the following error now:

```
"Sass -> CSS (may only compare numbers) styles/compass/css3/images"
```

Any ideas what this means or how to fix it?

**Comment by OysteinAmundsen** [comment]
Is there a release for this coming soon? I've noticed that this repository does not contain the latest version of the compass mixins. Will these be merged in as well?
