### ISSUE TITLE
URL support

### ISSUE THREAD

**Issue by terinjokes** [Igosuki/compass-mixins#20]
Continuing the discussion from https://github.com/Igosuki/compass-mixins/pull/18#issuecomment-59417195

---

It would be nice if Compass's URL functions were implemented, even if it comes down to variables we need to set before importing compass-mixins.

**Comment by OnkelTem** [comment]
Hm... can't we just define lacking functions in js?

**Comment by michaek** [comment]
I agree it's strange to not support everything from Compass, but this is a library that seeks to go halfway, as it would be prohibitive to support all of Compass. I'd say its intention is to provide a crutch to get to the point where your project no longer depends on Compass.

**Comment by gaomd** [comment]
@michaek The missing `image-url()` confused me, I believe I'm not alone, maybe we should note the incompleteness in the README.md.
