### ISSUE TITLE
Please release new version to npm

### ISSUE THREAD

**Issue by lxlang** [Igosuki/compass-mixins#26]
your npm version is outdated, https://www.npmjs.org/package/compass-mixins only offers 0.12.3

**Comment by estevejm** [comment]
+1

**Comment by lxlang** [comment]
please?

**Comment by michaelBenin** [comment]
bump.

**Comment by michaek** [comment]
@Igosuki needs to do this, or he needs to give me access on npm.

**Comment by michaek** [comment]
See https://github.com/Igosuki/compass-mixins/issues/21

**Comment by Geeza** [comment]
+1

**Comment by michaelBenin** [comment]
@lgosuki can you add @michaek or someone else as a publisher to this repository?

https://docs.npmjs.com/cli/owner

**Comment by lxlang** [comment]
+1

**Comment by lxlang** [comment]
Dear @Igosuki ,

it would be really really nice if you could do something about this.

**Comment by jiverson** [comment]
+1 Yes please bump.

**Comment by raymondmuller** [comment]
+1

**Comment by mingfang** [comment]
+1
this is ridiculous

**Comment by Igosuki** [comment]
Sorry guys, I should have noticed this even though I was deep in work. 
I release a 0.12.7 with the latest fixes and pushed it to npm (tested it's up with a fresh npm install).

**Comment by Igosuki** [comment]
By the way, the compass_latest branch is where it's at for the newer compass (1.0.3)
