### ISSUE TITLE
Wrong path in the images mixin

### ISSUE THREAD

**Issue by robertmwangi** [Igosuki/compass-mixins#27]
I just downloaded the library from bower (v. 0.12.3) and the sass compiler broke trying to compile the images mixin (lib/compass/css3/_images.scss). It could not import the hacks mixin in the utilities folder (lib/compass/utilities/general/_hacks.scss)
***Import path was***: "../../utilities/general/hacks"
***Changed to***: "../utilities/general/hacks"
That fixed it.
Thanks.

**Comment by Igosuki** [comment]
Hey thanks for the input, the fix was incorporated in the following tags.
