### ISSUE TITLE
image-width and image-height not calculating

### ISSUE THREAD

**Issue by dlip** [Igosuki/compass-mixins#29]
When I try to use image-width and image-height in my sass, the result is not calculated, rather the outputted css has the original image-width/height function calls inline. 

Does this library handle compass helper functions?

**Comment by michaek** [comment]
This library doesn't have access to the filesystem to check image dimensions, because it's trying to get close to compass using only sass script. Those would have to be implemented in C++ in libsass or using libsass's custom functions, when they land. https://github.com/sass/node-sass/issues/332

**Comment by ayush000** [comment]
@michaek Has the issue been fixed?

**Comment by ayush000** [comment]
@michaek I see that node-sass added custom functions, but I'm still not able to use image-width or image-height functions.

**Comment by ayush000** [comment]
For those who came across this issue, this library called [node-sass-asset-functions](https://github.com/fetch/node-sass-asset-functions) provides polyfills for all the functions. You can integrate it in your node-sass.
