### ISSUE TITLE
Compass color helpers missing

### ISSUE THREAD

**Issue by sir-dunxalot** [Igosuki/compass-mixins#31]
[Compass color helpers](http://compass-style.org/reference/compass/helpers/colors/) are a very useful part of Compass. I expect they could be written as functions to be a part of this library.

**Comment by sir-dunxalot** [comment]
Apologies - looks like there is a PR for this #24

Is it possible to get it merged soon?

**Comment by michaek** [comment]
It's merged. We'll have to sort out how to get this released, as it seems like @Igosuki is not interested in publishing to npm.

**Comment by sir-dunxalot** [comment]
Great, thanks for following up. What about Bower? I see there's a bower.json in the root and NPM might not be the prime candidate anyway given this package isn't much to do with node. Should definitely do a git release too.
