### ISSUE TITLE
bower install compass-mixins installs 1.0.2

### ISSUE THREAD

**Issue by devinus** [Igosuki/compass-mixins#46]
Which is the actual latest version?

**Comment by Igosuki** [comment]
Depends, which one of the compass versions you want. There is a work in progress that brings 0.12.7 fixes to 1.0.3.

**Comment by devinus** [comment]
@Igosuki Maybe I misunderstand, but isn't the latest Compass 1.0.3?

**Comment by Igosuki** [comment]
@devinus yes it is, but it requires us to implement a lot of placeholders, in the meantime you should use ~>0.12
