### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by talgautb** [Igosuki/compass-mixins#65]
Sorry but i don't understand how to add `compass-mixins` to own project.
added ```@import "compass"``` but there are errors :(
or `@import "../bower_components/compass-mixins/lib/compass"` ?
but is it ok ?!

**Comment by talgautb** [comment]
may be some info to Read.me - Usage ?

**Comment by luisfmsouza** [comment]
I've imported as your import... and I agree that it seems wrong.

**Comment by talgautb** [comment]
easy way to add only compass stylsheets on project)

**Comment by IAMtheIAM** [comment]
Please add usage instructions on the readme file. I agree it is confusing to implement.

**Comment by talgautb** [comment]
@Igosuki ?

**Comment by ItIsInspiring** [comment]
I agree with the comments. It is not easy to understand how to configure compass-mixin. 
it would be nice to have a more detailed tutorial about this plugin. 
Thanks

**Comment by kevinelliott** [comment]
Why did this get closed? The instructions were never added.

**Comment by KwesiJnr** [comment]
Was having trouble too, but here's how I got it to work:
1. Install the module via npm.
2. Inside the scss file, import the module, **e.g.** **@import "../../../../node_modules/compass-mixins/lib/compass";**

or if using bower:
1. add the module as a dependency in your bower.json file like so:
{
  "name": "imprv-workflow",
  "description": "Improved Workflow",
  "main": "build/index.html",
  "authors": [
    "Kwesi Jnr."
  ],
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  **"dependencies": {
    "compass-mixins": "~1.0.2"
  }**
}

2. Import it the same way as stated above but with bower_components in the path, not node_modules:
**@import "../../../../bower_components/compass-mixins/lib/compass";**


I observed that using bower_components was slightly faster than node_modules.
