### ISSUE TITLE
No input-placeholder mixin in compass/css3/user-interface

### ISSUE THREAD

**Issue by dsteinbach** [Igosuki/compass-mixins#74]
The latest has it but this package doesnt :(

https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/css3/_user-interface.scss

**Comment by xiaoDC** [comment]
me too!I have the same problem !

**Comment by phazei** [comment]
Duplicate of https://github.com/Igosuki/compass-mixins/issues/47

**Comment by xzyfer** [comment]
Fixed in v0.12.9
