### ISSUE TITLE
Filter mixin output with wrong syntax

### ISSUE THREAD

**Issue by samhenri** [Igosuki/compass-mixins#76]
I'm using python-libsass with compass mixins and when I tried to use grayscale filter, the output was:

```  -webkit-filter: compact(grayscale(100%), false, false, false, false, false, false, false, false, false);
  -moz-filter: compact(grayscale(100%), false, false, false, false, false, false, false, false, false);
  filter: compact(grayscale(100%), false, false, false, false, false, false, false, false, false);```

SCSS:
```@include filter(grayscale(100%));```

**Comment by buixuanhai** [comment]
I got the same problem when using box-shadow and single-text-shadow;
This is what it's compiled I saw using Chrome developer tool.
`text-shadow: compact(compact(0px 0px 1px false #aaa), false, false, false, false, false, false, false, false, false);`

**Comment by hansott** [comment]
+1

**Comment by xzyfer** [comment]
I believe this is fixed in the latest version. If this is not the case comment with an updated example and I'll reopen the issue.

**Comment by ZhouQunying** [comment]
Please reopen this issue, this bug still exists.
