### ISSUE TITLE
Broken on node-sass@^3.5.0

### ISSUE THREAD

**Issue by loganfsmyth** [Igosuki/compass-mixins#84]
Compiling this library with gulp-sass using node-sass 3.5.0, this is now broken and throwing

```
    node_modules/compass-mixins/lib/compass/functions/_lists.scss
Error: Functions may not be defined within control directives or other mixins.
        on line 81 of node_modules/compass-mixins/lib/compass/functions/_lists.scss
>>   @function compact($vars...) {
   --^
```

**Comment by loganfsmyth** [comment]
Sounds like it was a bug that this worked previously: https://github.com/sass/node-sass/issues/1456

**Comment by phazei** [comment]
+1
Please fix ASAP

**Comment by Shangbinbin** [comment]
+1

**Comment by hellonoam** [comment]
+1

**Comment by dschaller** [comment]
+1

**Comment by jmphilli** [comment]
+1

**Comment by cbrwizard** [comment]
+

**Comment by Kopatch** [comment]
+1

**Comment by lxlang** [comment]
+1

**Comment by VasuLief** [comment]
+1

**Comment by VasuLief** [comment]
you can replace this package with https://www.npmjs.com/package/compass-sass-mixins and it should work just fine

**Comment by fustic** [comment]
+1

**Comment by Predjo** [comment]
+1

**Comment by VasuLief** [comment]
you could also set a fixed version of node-sass@3.4.2 in your packages.json

**Comment by E-VANCE** [comment]
> you could also set a fixed version of node-sass@3.4.2 in your packages.json

Didn't do the trick for me...
+1

**Comment by dschaller** [comment]
If you're using grunt-sass it requires [node-sass](https://github.com/sindresorhus/grunt-sass/blob/master/package.json#L34) as well so you'd have to shrinkwrap in order to pin

**Comment by xzyfer** [comment]
Fix PR'd in https://github.com/Igosuki/compass-mixins/pull/86

**Comment by tonijn** [comment]
+1

**Comment by navgarcha** [comment]
+1

**Comment by fetis** [comment]
It's more than 11 days since fix is available. Any ideas when it'll be merged?

**Comment by mdular** [comment]
+1 for an ETA on the fix

**Comment by jsha09** [comment]
+1

**Comment by xzyfer** [comment]
PR is updated a passing. Turn out the transition mixin has never worked on offical Sass compiler.

**Comment by GFoley83** [comment]
+1

**Comment by GFoley83** [comment]
+1 I'm using `grunt-sass` like @dschaller which requires `node-sass`. Adding the `node-sass` dependency manually in the `package.json` solves the issue for me:
```js
  "devDependencies": {
    ...
    "node-sass": "3.4.2",
    ...
  }
```
Remember to either clean your `node_modules` folder or remove the `node-sass` folder first.

**Comment by orzarchi** [comment]
+1

**Comment by svaldi** [comment]
+1 Since, there is a problem with the node-sass also in the darwin-x64-48_binding.node when you use a node-sass 3.4.2 version. If we use 3.4.2 temporary this is not a favorable option.

**Comment by jeanschmidt** [comment]
+1

**Comment by ale-grosselle** [comment]
+1, please!

**Comment by runderworld** [comment]
+1 por favor!

**Comment by henk23** [comment]
+1

**Comment by xzyfer** [comment]
Hello everyone, I've gotten in contact with @Igosuki and I'll now be helping out maintaining this project. This should prevent further breakages.

**Comment by xzyfer** [comment]
compass-mixins@0.12.8 has been released

**Comment by svaldi** [comment]
Thank you so much to everyone!!!!!

**Comment by ismaail** [comment]
Hi, I'm getting this error trying to compile [mdb.scss from MDBootstrap](https://github.com/mdbootstrap/bootstrap-material-design/blob/master/scss/mdb.scss)

```
Module build failed: ModuleBuildError: Module build failed: 
    @function set-notification-text-color($color) {
             ^
      Functions may not be defined within control directives or other mixins.
      in /home/user/project/assets/MDBootstrap/scss/core/_mixins.scss (line 215, column 15)

```

- compass-mixins: ^0.12.10
- node-sass: ^4.8.3
- node version: v9.10.1
- npm version: 5.8.0

**Comment by xzyfer** [comment]
This package is no longer supported. We recommended using http://bourbon.io
