### ISSUE TITLE
Invalid Sass

### ISSUE THREAD

**Issue by xzyfer** [Igosuki/compass-mixins#85]
The following is not valid Sass code

```sass
@if not(function-exists(compact)) {
  @function compact($vars...) {
    $list: ();
    @each $var in $vars {
        @if $var {
            $list: append($list, $var, comma);
        }
    }
    @return $list;
  }
}
```

From: https://github.com/Igosuki/compass-mixins/blob/8d93bef3e982cba3420bd16c04a99fabf4e3399e/lib/compass/functions/_lists.scss#L80-L90

This code produces the following error in Sass

```
Error: Functions may not be defined within control directives or other mixins.
        on line 2 of test.scss
  Use --trace for backtrace.
```

This previously worked in Node Sass due to a bug in LibSass which has since been fixed. As a result this library no longer compiles.

**Comment by dclowd9901** [comment]
+1, got this error when node-sass updated to 3.5 from 3.4.2

**Comment by xzyfer** [comment]
Fix PR'd in https://github.com/Igosuki/compass-mixins/pull/86

**Comment by xzyfer** [comment]
Hello everyone, I've gotten in contact with @Igosuki and I'll now be helping out maintaining this project. This should prevent further breakages.

**Comment by xzyfer** [comment]
[compass-mixins@0.12.8](https://github.com/Igosuki/compass-mixins/releases/tag/v0.12.8) has been released
